import sys
import json
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

def generate_pptx(data):
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = data.get("title", "Presentation")
    subtitle.text = "Generated by Horizon AI — Premium Intelligence Engine"

    # Content Slides
    for slide_data in data.get("slides", []):
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]

        title_shape.text = slide_data.get("title", "")
        
        tf = body_shape.text_frame
        tf.text = slide_data.get("intro", "")
        
        for bullet in slide_data.get("bullets", []):
            p = tf.add_paragraph()
            p.text = bullet
            p.level = 1

    filename = data.get("filename", "presentation.pptx")
    if not filename.endswith(".pptx"):
        filename += ".pptx"
    
    output_path = data.get("output_path", filename)
    prs.save(output_path)
    print(output_path)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(1)
    
    try:
        raw_data = sys.argv[1]
        data = json.loads(raw_data)
        generate_pptx(data)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
